volumes:
  prometheus_volume:
  grafana_volume:

services:
  # see: http://localhost:9091/
  pushgateway:
    image: prom/pushgateway
    expose:
      - 9091
    ports:
      - "9091:9091"


  prometheus:
    image: prom/prometheus:v2.40.2
    expose:
      - 9090
    ports:
      - "9090:9090"
    volumes:
      - prometheus_volume:/prometheus
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml

  # see: http://localhost:3000/
  grafana:
    image: grafana/grafana:11.4.0
    depends_on:
      - prometheus
    volumes:
      - grafana_volume:/var/lib/grafana
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
       - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    ports:
      - "3000:3000"
