global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "pushgateway"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "pushgateway:9091"
        labels:
          app: "pushgateway"
